CREATE TABLE rubrics (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	name TEXT(50) NOT NULL
);
CREATE TABLE news (
	id	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	head	TEXT(256) NOT NULL,
	text	TEXT NOT NULL,
	link	TEXT NOT NULL,
	date	TEXT(10) NOT NULL,
	rubric_id	INTEGER NOT NULL
);


ALTER TABLE news ADD FOREIGN KEY (rubric_id) REFERENCES rubric(id); 